language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - python setup.py install
  - pip install coverage coveralls
  - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys
  - cat ~/.ssh/authorized_keys
  - ssh -o StrictHostKeyChecking=no localhost 'echo test'
  - cat ~/.ssh/known_hosts
# command to run tests
script:
  - python -m unittest discover
